import type { NextPage } from "next";
import Head from "next/head";
import {
  HomeContainer,
  HomeCTAContainer,
  EventsCarousel,
  SigninContainer,
  ContentContainer,
} from "../styles/Home";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Modal } from "react-bootstrap";
import { useState } from "react";

const Home: NextPage = () => {
  const settings = {
    dots: false,
    infinite: true,
    speed: 500,
    slidesToShow: 4,
    slidesToScroll: 1,
  };

  const [show, setShow] = useState(false);

  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  return (
    <>
      <HomeContainer>
        <Head>
          <title>BUKEDIT</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
          <h1>BUKEDIT</h1>
          <ul>
            <li>Events</li>
            <li>About</li>
            <li>Register your service</li>
            <li>
              <button type="button" onClick={handleShow}>
                Sign in
              </button>
            </li>
          </ul>
        </header>
        <HomeCTAContainer>
          <div className="search-box">
            <h1>WHAT EVENT ARE YOU PLANNING?</h1>
            <div className="input-box">
              <input type="text" placeholder="Search for an event" />
              <button>Search</button>
            </div>
          </div>
          <div className="image-box" />
        </HomeCTAContainer>
        <EventsCarousel>
          <Slider {...settings}>
            <div className="carousel-item">
              <div className="image-iten-list" />
              <p>Wedding</p>
            </div>
            <div className="carousel-item">
              <div className="image-iten-list" />
              <p>Birthday</p>
            </div>
            <div className="carousel-item">
              <div className="image-iten-list" />
              <p>Party</p>
            </div>
            <div className="carousel-item">
              <div className="image-iten-list" />
              <p>Corporate Dinner</p>
            </div>
            <div className="carousel-item">
              <div className="image-iten-list" />
              <p>Text</p>
            </div>
          </Slider>
        </EventsCarousel>
        <ContentContainer>
          <div>
            <p className="main">
              Let us do the <br /> hard work
            </p>
            <p className="secondary">
              Bukedit finds all the service providers
              <br />
              you need for your specific event
            </p>
          </div>
        </ContentContainer>
      </HomeContainer>
      <Modal
        show={show}
        onHide={handleClose}
        aria-labelledby="contained-modal-title-vcenter"
        centered
      >
        <Modal.Body>
          <SigninContainer className="signin-form">
            <h1>Sign in or Register</h1>
            <input placeholder="Email" type="email" />
            <input placeholder="Password" type="password" />
            <button type="button">Sign in</button>
            <p className="forgot-password">Forgot Password ?</p>
            <hr />
            <p className="new-account">
              Don’t have an account? <span>Sign Up</span>
            </p>
          </SigninContainer>
        </Modal.Body>
      </Modal>
    </>
  );
};

export default Home;
